### ISSUE TITLE
vt_num inconsistent type

### ISSUE THREAD

**Issue by edne** [alberto-antonietti/CerebNEST#13]
The `vt_num` parameters is required to be a long in `volume_transmitter.cpp` and a double in the synapses definitions

https://github.com/alberto-antonietti/CerebNEST/search?l=C%2B%2B&q=vt_num

**Comment by alberto-antonietti** [comment]
Changed all vt_num to `long` since they should be integer numbers.

**Comment by alberto-antonietti** [comment]
With the changes, NEST complains when trying to `Connect `

`nest.Connect(PRE, POST, "all_to_all", {"model": 'stdp_synapse_sinexp', "vt_num": 0})`

Raises:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/alberto/workspace/nest-simulator-2.18.0/b/lib/python3.5/site-packages/nest/ll_api.py", line 246, in stack_checker_func
>     return f(*args, **kwargs)
>   File "/home/alberto/workspace/nest-simulator-2.18.0/b/lib/python3.5/site-packages/nest/lib/hl_api_connections.py", line 362, in Connect
>     sr('Connect')
>   File "/home/alberto/workspace/nest-simulator-2.18.0/b/lib/python3.5/site-packages/nest/ll_api.py", line 132, in catching_sli_run
>     raise exceptionCls(commandname, message)
> nest.ll_api.TypeMismatch: ('TypeMismatch in Connect_g_g_D_D: Expected datatype: integertype\nProvided datatype: doubletype', 'TypeMismatch', <SLILiteral: Connect_g_g_D_D>, ': Expected datatype: integertype\nProvided datatype: doubletype')

**Comment by alberto-antonietti** [comment]
Calling a `SetStatus` a posteriori works fine,
